---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: git-repo
outputs:
  - name: out
run:
  path: ./gradlew
  args: ["build", "--no-daemon"]
  dir: git-repo

