---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: ((openjdk-tag))
inputs:
  - name: build-jdk8
run:
  path: find . -type f
  args: []
  dir: git-repo

