email-server: "smtp.svc.pivotal.io"
email-from: "ci@spring.io"
email-to: ["fhanik@pivotal.io"]
github-repo: "https://github.com/fhanik/spring-security.git"
github-repo-name: "fhanik/spring-security"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "feature/concourse"
build-name: "spring-security"
pipeline-name: "spring-security"
concourse-url: "https://ci.spring.io"
bintray-subject: "spring"
bintray-repo: "jars"
task-timeout: 1h00m
openjdk-8-tag: 8-jdk
openjdk-9-tag: 9-jdk
#the tag 10-jdk throws a generics error during compilation, try to use 10-jdk-experimental
openjdk-10-tag: 10-jdk
openjdk-11-tag: 11-jdk
openjdk-12-tag: 12-jdk
build-java-8-cmd: build
build-java-11-cmd: test
build-arg-empty: "-Dplaceholder"

