github-repo-name: "fhanik/spring-security"
branch: "feature/concourse"

github-repo: "https://github.com/fhanik/spring-security.git"
task-timeout: 1h00m

openjdk-8-tag: 8-jdk
openjdk-9-tag: 9-jdk
openjdk-10-tag: 10-jdk
openjdk-11-tag: 11-jdk
openjdk-12-tag: 12-jdk
build-java-8-cmd: build
build-java-11-cmd: test
build-java-check-cmd: check
build-arg-empty: "-Dplaceholder"

spring-gpg-key-id: 9A2C7A98E457C53D
