resources:
  - name: git-repo
    type: git
    icon: github-circle
    source:
      uri: ((github-repo))
      branch: ((branch))

jobs:
  - name: run-build
    plan:
      - get: git-repo
        trigger: true
      - task: build
        file: git-repo/ci/tasks/build.yml

