resources:
  - name: git-repo
    type: git
    source:
      uri: ((github-repo))
      branch: ((branch))

jobs:
  - name: run-build
    plan:
      - get: git-repo
        trigger: true
      - in_parallel:
          - task: build-jdk-8
            file: git-repo/ci/tasks/build.yml
            vars: {openjdk-tag: ((openjdk-8-tag))}
          - task: build-jdk-12
            file: git-repo/ci/tasks/build.yml
            vars: {openjdk-tag: ((openjdk-12-tag))}


