resources:
  - name: git-repo
    type: git
    source:
      uri: ((github-repo))
      branch: ((branch))
  - name: git-pull-request
    type: pull-request
    icon: source-pull
    source:
      repo: ((github-repo-name))
      base: ((branch))
      ignore_paths: ["ci/*"]

jobs:
  - name: build-check
    plan:
      - get: git-repo
        trigger: true
      - task: build-jdk-8
        file: git-repo/ci/tasks/build.yml
        vars: {openjdk-tag: ((openjdk-8-tag)), build-cmd: check}
        timeout: ((task-timeout))
  - name: build-jdk8
    plan:
      - get: git-repo
        trigger: true
      - task: build-jdk-8
        file: git-repo/ci/tasks/build.yml
        vars: {
          openjdk-tag: ((openjdk-8-tag)),
          build-cmd: ((build-java-8-cmd)),
          build-arg1: ((build-arg1)),
          build-arg2: ((build-arg2)),
          build-arg3: ((build-arg3)),
          build-arg4: ((build-arg4)),
        }
        timeout: ((task-timeout))
  - name: build-snapshot
    plan:
    - get: git-repo
      trigger: true
    - task: build-jdk-8
      file: git-repo/ci/tasks/build.yml
      vars: {
        openjdk-tag: ((openjdk-8-tag)),
        build-cmd: ((build-java-11-cmd)),
        build-arg1: "-PforceMavenRepositories=snapshot",
        build-arg2: "-PspringVersion='5.+'",
        build-arg3: "-PreactorVersion=Dysprosium-BUILD-SNAPSHOT",
        build-arg4: "-PspringDataVersion=Lovelace-BUILD-SNAPSHOT",
      }
      timeout: ((task-timeout))
  - name: build-jdk9
    plan:
      - get: git-repo
        trigger: true
      - task: build-jdk-9
        file: git-repo/ci/tasks/build.yml
        vars: {
          openjdk-tag: ((openjdk-9-tag)),
          build-cmd: ((build-java-8-cmd)),
          build-arg1: ((build-arg1)),
          build-arg2: ((build-arg2)),
          build-arg3: ((build-arg3)),
          build-arg4: ((build-arg4)),
        }
        timeout: ((task-timeout))
  - name: build-jdk10
    plan:
      - get: git-repo
        trigger: true
      - task: build-jdk-10
        file: git-repo/ci/tasks/build.yml
        vars: {
          openjdk-tag: ((openjdk-10-tag)),
          build-cmd: ((build-java-11-cmd)),
          build-arg1: ((build-arg1)),
          build-arg2: ((build-arg2)),
          build-arg3: ((build-arg3)),
          build-arg4: ((build-arg4)),
        }
        timeout: ((task-timeout))
  - name: build-jdk11
    plan:
      - get: git-repo
        trigger: true
      - task: build-jdk-11
        file: git-repo/ci/tasks/build.yml
        vars: {
          openjdk-tag: ((openjdk-11-tag)),
          build-cmd: ((build-java-11-cmd)),
          build-arg1: ((build-arg1)),
          build-arg2: ((build-arg2)),
          build-arg3: ((build-arg3)),
          build-arg4: ((build-arg4)),
        }
        timeout: ((task-timeout))
  - name: build-jdk12
    plan:
      - get: git-repo
        trigger: true
      - task: build-jdk-12
        file: git-repo/ci/tasks/build.yml
        vars: {
          openjdk-tag: ((openjdk-12-tag)),
          build-cmd: ((build-java-11-cmd)),
          build-arg1: ((build-arg1)),
          build-arg2: ((build-arg2)),
          build-arg3: ((build-arg3)),
          build-arg4: ((build-arg4)),
        }
        timeout: ((task-timeout))
  - name: build-passed
    plan:
      - get: git-repo
        trigger: true
        passed: [build-check, build-jdk8, build-jdk9, build-jdk11, build-jdk12]
      - task: build-passed
        file: git-repo/ci/tasks/build-passed.yml
        vars: {openjdk-tag: ((openjdk-8-tag))}
        timeout: ((task-timeout))
  - name: build-pull-requests
    serial: true
    public: true
    plan:
      - get: git-repo
        resource: git-pull-request
        trigger: true
        version: every
      - task: build-jdk-8-pr
        file: git-repo/ci/tasks/build.yml
        vars: {openjdk-tag: ((openjdk-8-tag))}
        timeout: ((task-timeout))

groups:
  - name: "Build"
    jobs: ["build-check", "build-jdk8", "build-jdk9", "build-jdk10", "build-jdk11", "build-jdk12", "build-passed", "build-snapshot"]
  - name: "Build Pull Requests"
    jobs: ["build-pull-requests"]

